/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haoch' at '11/9/15 3:36 PM' with Gradle 2.8
 *
 * @author haoch, @date 11/9/15 3:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
